Login_Signup_Close_Button_Popup = //span[@class=\"logSprite icClose\"]
From_InputBox = //input[@id=\"fromCity\"]
From_TextBox = //input[@placeholder=\\"From\\"]
From_CityName= //div[@class=\"react-autosuggest__section-container react-autosuggest__section-container--first\"]//ul//li)[1]
To_InputBox = //div[@class=\"flt_fsw_inputBox searchToCity inactiveWidget \"]//input
To_TextBox = //input[@autocomplete=\"off\"]
To_CityName =//div[@class=\"makeFlex column flexOne\"])[1]"
Departure_Date= //div[@class=\"DayPicker-Month\"])[1]//div[@class=\"DayPicker-Body\"]//div[@aria-label=\"Mon Jan 08 2026\"]
Search_Button= //a[contains(text(),\"Search\")]"